<a href="https://colab.research.google.com/github/Shavkatov-dev/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [2]:
import numpy as np

arr = np.array([1,3,5,])
print('numpy_array:', arr)

numpy_array: [1 3 5]


In [4]:

arr2 = np.array([[1,3,5,],[4,6,8]])
print('numpy_array:', arr2)

arr2.shape

numpy_array: [[1 3 5]
 [4 6 8]]


(2, 3)

In [5]:
#dtype

a = np.array([1,2,3])
print(a.dtype)


int64


In [7]:
#reshape


a = np.array([1,2,3, 4, 5, 6])
b = a.reshape(2,3)
print('reshaped-array', b)


reshaped-array [[1 2 3]
 [4 5 6]]


In [8]:
# astype

a = np.array([1,2,3])
b = a.astype(float)
print('reshaped-array', b)


reshaped-array [1. 2. 3.]


In [10]:
#np.zeros, np.ones

z = np.zeros((7, 4))
o = np.ones((4, 7))

print("zeros", z)
print("ones", o)

zeros [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [11]:
#ndim


a = np.array([1,2,3])
print(a.ndim)

1


In [13]:
#arrange


a = np.arange(1, 6)
print("arange", a)

arrange [1 2 3 4 5]


In [14]:
#sum(), mean(), max(), min()

a = np.array([1, 2, 3, 4, 5])

print('sum', a.sum())
print('mean', a.mean())
print('max', a.max())
print('min', a.min())

sum 15
mean 3.0
max 5
min 1


In [15]:
#flatten
a = np.array([[1, 2 ,3], [1, 2 ,3]])

print('flatten', a.flatten())

flatten [1 2 3 1 2 3]


In [16]:
#t (transpose)
a = np.array([[1, 2],[3, 4]])

print('transpose', a.transpose())

transpose [[1 3]
 [2 4]]


In [17]:
#dot
a = np.array([[1, 2],[3, 4]])
b = np.array([[1, 2],[3, 4]])

print('dot/multiply', a.dot(b))

dot/multiply [[ 7 10]
 [15 22]]


In [18]:
#random.rand()
a = np.random.rand(2, 3)
print('random_rand,', a)

random_rand, [[0.42511094 0.36413522 0.77933343]
 [0.27388212 0.35422049 0.31988232]]
